export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_FAIL =  'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';

export const AUTH_ERROR = 'AUTH_ERROR';

export const PRESCRIPTION_SUBMITTED =  'PRESCRIPTION_SUBMITTED ';

export const RETRIEVE_PRESCRIPTION =  'RETRIEVE_PRESCRIPTION ';

export const VIEW_PRESCRIPTION =  'VIEW_PRESCRIPTION ';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_FAIL = 'LOGIN_FAIL'